# https://docs.codecov.com/docs/codecov-yaml
# https://docs.codecov.com/docs/common-recipe-list
coverage:
  status:
    project:
      default:
        # auto compares coverage to the previous base commit
        target: auto
        # flag any drop in coverage
        threshold: 0%
        # use base commit automatically
        base: auto
        # non-blocking coverage checks
        informational: true
    patch:
      default:
        # non-blocking coverage checks
        informational: true

comment:
  # comment format
  layout: "diff, flags, files"
  # default behavior for posting comments
  behavior: default
  # only post the comment if coverage changes
  require_changes: false
  # require base report
  require_base: false
  # require head report
  require_head: true
  # only show coverage on the git diff aka patch coverage
  hide_project_coverage: false
