# compose.yaml overrides for local development
services:
  # Sketched client
  client:
    image: "shevtsod/sketched-client:latest"
    pull_policy: "build"
    # Build image from Dockerfile
    build:
      dockerfile: "packages/client/Dockerfile"
      target: "development"
    # Load environment variables from file
    env_file:
      - path: ".env"
        required: false
    # Override environment variables
    environment:
      HOST: "server"
    ports:
      - "5173:5173"

  # Sketched server
  server:
    image: "shevtsod/sketched-server:latest"
    pull_policy: "build"
    # Build image from Dockerfile
    build:
      dockerfile: "packages/server/Dockerfile"
      target: "development"
    ports:
      - "3000:3000"
      # Node.js debugger
      - "9229:9229"

  # database
  # https://hub.docker.com/_/postgres
  db:
    ports:
      - "${DB_PORT:-5432}:5432"

  # cache
  # https://hub.docker.com/r/valkey/valkey/
  cache:
    ports:
      - "${CACHE_PORT:-6379}:6379"

  # object store
  # https://hub.docker.com/r/minio/minio
  objects:
    ports:
      - "9000:9000"
      # web UI
      - "9001:9001"
